name: Check format and test build
'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.10.2
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Run tests
        run: |
          pnpm run lint:check
          pnpm run prettier:check
          pnpm run test
          pnpm run build
      - name: Upload playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1